syntax on
set bg=dark
set shiftwidth=4
set tabstop=4
set softtabstop=4
set foldlevel=10
set foldmethod=indent
set shortmess=atI
set autoindent
set expandtab
set hidden
set hls
set ignorecase
set incsearch
set modeline
set noswf
set noerrorbells
set visualbell
set ruler
set smartcase
set smarttab
set title
set wildmenu
filetype plugin on
           
runtime mappings.vim
runtime mousescroll.vim
runtime cruft.vim

map <F1> :w<CR>
imap <F1> <Esc>:w<CR>

au! BufWritePost .vimrc source %

let g:netrw_banner       = 0
let g:netrw_keepdir      = 0
let g:netrw_liststyle    = 1 " or 3
let g:netrw_sort_options = 'i'
let g:netrw_browse_split = 4

"autocmd VimEnter * if !argc() | Explore | endif
autocmd VimEnter * if isdirectory(expand('<afile>')) | Explore | endif

" Toggle Vexplore with Ctrl-E
function! ToggleVExplorer()
  if exists("t:expl_buf_num")
      let expl_win_num = bufwinnr(t:expl_buf_num)
      if expl_win_num != -1
          let cur_win_nr = winnr()
          exec expl_win_num . 'wincmd w'
          close
          exec cur_win_nr . 'wincmd w'
          unlet t:expl_buf_num
      else
          unlet t:expl_buf_num
      endif
  else
      exec '1wincmd w'
      Vexplore
      let t:expl_buf_num = bufnr("%")
  endif
endfunction
map <silent> <F2> :call ToggleVExplorer()<CR>
map <silent> <C-E> :call ToggleVExplorer()<CR>
