#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding 16
bspc config split_ratio         0.52
bspc config border_width        2
bspc config window_gap          2
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true

# Interpret two consecutive identical use messages as an alternate message.
bspc config auto_alternate true

# Interpret two consecutive identical presel messages as a cancel message
bspc config auto_cancel true

bspc config normal_border_color  gray33
bspc config focused_border_color gray66
bspc config presel_border_color  gray99


bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# do this here so that we know the NetWM anchor window is up
~/bin/java_nonreparenting_wm_hack.sh

# manage windows left from previous session
bspc control --adopt-orphans
