#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc config top_padding 24
#bspc config -m LVDS1 top_padding 24
#bspc config -m DP1 top_padding 24
#bspc config -m VGA1 top_padding 24
bspc config split_ratio         0.52
bspc config border_width        2
bspc config window_gap          2
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

# Interpret two consecutive identical use messages as an alternate message.
bspc config auto_alternate true

# Interpret two consecutive identical presel messages as a cancel message
bspc config auto_cancel true

bspc config normal_border_color  gray11
bspc config focused_border_color gray55
bspc config presel_border_color  gray99


bspc rule -a Gimp follow=on floating=on
bspc rule -a mplayer2 floating=on
bspc rule -a tomboy floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a pavucontrol floating=on

# stick+float hangouts chat windows
bspc rule -a crx_nckgahadagoaajjgafhacjanaoiihapd  floating=on sticky=on

# do this here so that we know the NetWM anchor window is up
~/bin/java_nonreparenting_wm_hack.sh

# manage windows left from previous session
bspc control --adopt-orphans
