#!/bin/sh

#FIRST_DESK=I
#REMAINING_DESKS="II III IV V VI VII VIII IX"
FIRST_DESK=1
REMAINING_DESKS="$(seq 2 9) 0"
bspc desktop Desktop01 -n $FIRST_DESK

bspc monitor -a $REMAINING_DESKS
bspc monitor -p 18 0 0 0

bspc config split_ratio         0.52
bspc config border_width        2
bspc config window_gap          12
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true

# Interpret two consecutive identical use messages as an alternate message.
bspc config auto_alternate true

# Interpret two consecutive identical presel messages as a cancel message
bspc config auto_cancel true

bspc config normal_border_color  gray33
bspc config focused_border_color gray66
bspc config presel_border_color  gray99

bspc rule -a Thunar --floating
bspc rule -a Transmission --floating
bspc rule -a feh --floating
bspc rule -a Gimp -d 8 --floating
