# Path to your oh-my-zsh configuration.
ZSH=$HOME/config/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
#ZSH_THEME=random

[[ -z $ZSH_THEME ]] && ZSH_THEME=rgm

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias vi=vim
#alias ssh=~/config/bin/moshalias.pl

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

DISABLE_VENV_CD=1
HIST_STAMPS="yyyy-mm-dd"


# Uncomment following line if you want red dots to be displayed while waiting for completion
#COMPLETION_WAITING_DOTS="true"

plugins=(git pip virtualenvwrapper sublime docker fabric jira)

source $ZSH/oh-my-zsh.sh

#PATH="$HOME/bin:$PATH"

# Sets PERL5LIB and adds bin dir to PATH / cpanm --local-lib=~/perl5 local::lib
#test -d ~/perl5 && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)

#export PERL_LOCAL_LIB_ROOT="$PERL_LOCAL_LIB_ROOT:/home/spowers/perl5";
#export PERL_MB_OPT="--install_base /home/spowers/perl5";
#export PERL_MM_OPT="INSTALL_BASE=/home/spowers/perl5";
#export PERL5LIB="/home/spowers/perl5/lib/perl5:$PERL5LIB";
#export PATH="/usr/local/cassandra/bin:/home/spowers/perl5/bin:$PATH";

test -f ~/.gcal && cat ~/.gcal

dirdiff () { diff -ui <(cd "$1" && find | sort -f) <(cd "$2" && find | sort -f) }

setopt autopushd


#go-up () {
#cd ..
#zle reset-prompt
#}; zle -N go-up

#go-back () {
#popd
#zle reset-prompt
#}; zle -N go-back


# shift+up arrow
#bindkey '^[[1;2A' go-up

# shift+left arrow
#bindkey '^[[1;2D' go-back
alias adb=~/Downloads/android-sdk-linux/platform-tools/adb

